export const chainData = [
  {
    chainId: 1,
    url: "https://etherscan.io",
    name: "Ethereum",
    scan: "Etherscan.io",
    nativeToken: "ETH",
    base_fee: 0.0002,
  },
  {
    chainId: 10,
    url: "https://optimistic.etherscan.io",
    name: "Optimism",
    scan: "Optimistic.etherscan.io",
    nativeToken: "ETH",
    base_fee: 0.0002,
  },
  {
    chainId: 420,
    url: "https://goerli-optimism.etherscan.io",
    name: "Optimism goerli",
    scan: "Goerli.optimistic.etherscan.io",
    nativeToken: "ETH",
    base_fee: 0.0002,
  },
  {
    chainId: 137,
    url: "https://polygonscan.com/",
    name: "Polygon",
    scan: "Polygonscan.com",
    nativeToken: "MATIC",
    base_fee: 0.5,
  },
  {
    chainId: 80001,
    url: "https://mumbai.polygonscan.com",
    name: "Polygon mumbai",
    scan: "Mumbai.polygonscan.com",
    nativeToken: "MATIC",
    base_fee: 0.0002,
  },
  {
    chainId: 8453,
    url: "https://basescan.org",
    name: "Base",
    scan: "Basescan.org",
    nativeToken: "ETH",
    base_fee: 0.0002,
  },
  {
    chainId: 84531,
    url: "https://goerli.basescan.org",
    name: "Base goerli",
    scan: "Goerli.basescan.org",
    nativeToken: "ETH",
    base_fee: 0.0002,
  },
];
